# Generated by Django 3.1.5 on 2021-01-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_workplaces_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingworkplace',
            name='datetime_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookingworkplace',
            name='datetime_to',
            field=models.DateTimeField(),
        ),
    ]
